In [1]:
%matplotlib inline

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets


In [23]:
AND=pd.DataFrame({'x1':(0,0,1,1), 'x2':(0,1,0,1) ,'y':(0,0,0,1)})

In [24]:
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [33]:
#wieghts to initizlize 

weights=np.random.randn(3)*1e-4
weights

array([ 4.12816600e-05,  4.70834163e-05, -5.84509843e-05])

In [34]:
#simplest activation function

g=lambda inputs, weights:np.where(np.dot(inputs,weights)>0,1,0)


In [ ]:
#WN=W0-n dell e
#UPDATE WEIGHTS

In [ ]:
### creates 2d array inputs=np.c_[inputs,-np.ones((len(inputs),1))] 
# x1 x2 bias


In [14]:
a=np.c_[inputs,-np.ones((len(inputs),1))]
a

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [15]:
##np.dot(a,w) #4x3 and 3x1 
#array([-5.00054503e-01, -2.07228220e-04, -2.49964969e-01,  2.49882306e-01])
## therefore  from ouput we get 0,0,0,1

array([-5.00054503e-01, -2.07228220e-04, -2.49964969e-01,  2.49882306e-01])

In [35]:
def train(inputs,target,weights,eta,n_iter):
    inputs=np.c_[inputs,-np.ones((len(inputs),1))]
    for n in range(n_iter):
        act=g(inputs,weights);
        print(n,act)
        weights-=eta*np.dot(np.transpose(inputs),act-target)
        print(n,weights)
    return (weights)

In [36]:
inputs=AND[['x1','x2']]
target=AND['y']
w = train(inputs, target, weights, eta=.034, n_iter=10)
target

0 [1 1 1 1]
0 [-0.03395872 -0.03395292  0.10194155]
1 [0 0 0 0]
1 [4.12816600e-05 4.70834163e-05 6.79415490e-02]
2 [0 0 0 0]
2 [0.03404128 0.03404708 0.03394155]
3 [0 1 1 1]
3 [4.12816600e-05 4.70834163e-05 1.01941549e-01]
4 [0 0 0 0]
4 [0.03404128 0.03404708 0.06794155]
5 [0 0 0 1]
5 [0.03404128 0.03404708 0.06794155]
6 [0 0 0 1]
6 [0.03404128 0.03404708 0.06794155]
7 [0 0 0 1]
7 [0.03404128 0.03404708 0.06794155]
8 [0 0 0 1]
8 [0.03404128 0.03404708 0.06794155]
9 [0 0 0 1]
9 [0.03404128 0.03404708 0.06794155]


0    0
1    0
2    0
3    1
Name: y, dtype: int64